[package]
name = "img-resize-api"
version = "0.1.0"
authors = ["Xavier Di Domizio <xdidomizio@netwo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image= "*"
actix-web = "*"
serde = "*"